//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XLocate.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://127.0.0.1:50010/xmap/ws/XMap")]
        public string xmap {
            get {
                return ((string)(this["xmap"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://127.0.0.1:50020/xlocate/ws/XLocate")]
        public string xlocate {
            get {
                return ((string)(this["xlocate"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SEARCH_BINARY {
            get {
                return ((bool)(this["SEARCH_BINARY"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SEARCH_PHOETIC {
            get {
                return ((bool)(this["SEARCH_PHOETIC"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SEARCH_FUZZY {
            get {
                return ((bool)(this["SEARCH_FUZZY"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool STREET_RETURNALLHNR {
            get {
                return ((bool)(this["STREET_RETURNALLHNR"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CITY_RETURNALLCITY2 {
            get {
                return ((bool)(this["CITY_RETURNALLCITY2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MULTIWORDINDEX_ENABLE {
            get {
                return ((bool)(this["MULTIWORDINDEX_ENABLE"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool POSTCODE_AGGREGATE {
            get {
                return ((bool)(this["POSTCODE_AGGREGATE"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool INTERSECTIONS_ENABLE {
            get {
                return ((bool)(this["INTERSECTIONS_ENABLE"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SearchOptions {
            get {
                return ((bool)(this["SearchOptions"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ReverseSearchOptions {
            get {
                return ((bool)(this["ReverseSearchOptions"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CallerContextProperties {
            get {
                return ((bool)(this["CallerContextProperties"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int ENGINE_TOLERANCE {
            get {
                return ((int)(this["ENGINE_TOLERANCE"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int ENGINE_TARGETSIZE {
            get {
                return ((int)(this["ENGINE_TARGETSIZE"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DEF")]
        public string RESULT_LANGUAGE {
            get {
                return ((string)(this["RESULT_LANGUAGE"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DEF")]
        public string RevRESULT_LANGUAGE {
            get {
                return ((string)(this["RevRESULT_LANGUAGE"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("L")]
        public string COUNTRY {
            get {
                return ((string)(this["COUNTRY"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string STATE {
            get {
                return ((string)(this["STATE"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5447")]
        public string POSTCODE {
            get {
                return ((string)(this["POSTCODE"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Wellenstein")]
        public string CITY {
            get {
                return ((string)(this["CITY"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CITY2 {
            get {
                return ((string)(this["CITY2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Rue de la Moselle")]
        public string STREET {
            get {
                return ((string)(this["STREET"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public string HOUSENR {
            get {
                return ((string)(this["HOUSENR"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6372253.889732955")]
        public double LOCATION_Y {
            get {
                return ((double)(this["LOCATION_Y"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("681426.23948316672")]
        public double LOCATION_X {
            get {
                return ((double)(this["LOCATION_X"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string HNR_OFFSET {
            get {
                return ((string)(this["HNR_OFFSET"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("default")]
        public string Profile {
            get {
                return ((string)(this["Profile"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int CoordFormat {
            get {
                return ((int)(this["CoordFormat"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ASTERISKMODE {
            get {
                return ((int)(this["ASTERISKMODE"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int COUNTRY_CODETYPE {
            get {
                return ((int)(this["COUNTRY_CODETYPE"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SWAPANDSPLITMODE {
            get {
                return ((int)(this["SWAPANDSPLITMODE"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int STREET_HNRPOSITION {
            get {
                return ((int)(this["STREET_HNRPOSITION"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int RevCOUNTRY_CODETYPE {
            get {
                return ((int)(this["RevCOUNTRY_CODETYPE"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int ResponseGeometry {
            get {
                return ((int)(this["ResponseGeometry"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string ENGINE_FILTERMODE {
            get {
                return ((string)(this["ENGINE_FILTERMODE"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool displayMap {
            get {
                return ((bool)(this["displayMap"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool REQUEST_ADDFITIONALFIELDS {
            get {
                return ((bool)(this["REQUEST_ADDFITIONALFIELDS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PTVXLocate Testclient")]
        public string CallerContext_Log1 {
            get {
                return ((string)(this["CallerContext_Log1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CallerContext_Log2 {
            get {
                return ((string)(this["CallerContext_Log2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CallerContext_Log3 {
            get {
                return ((string)(this["CallerContext_Log3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ENGINE_SEARCHDETAILLEVEL {
            get {
                return ((string)(this["ENGINE_SEARCHDETAILLEVEL"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ENGINE_SEARCHRANGE {
            get {
                return ((string)(this["ENGINE_SEARCHRANGE"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseNewFields {
            get {
                return ((bool)(this["UseNewFields"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("default")]
        public string MapProfile {
            get {
                return ((string)(this["MapProfile"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Malmö")]
        public string SingleFieldText {
            get {
                return ((string)(this["SingleFieldText"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("S")]
        public string SingleFieldCountry {
            get {
                return ((string)(this["SingleFieldCountry"]));
            }
            set {
                this["SingleFieldCountry"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(",")]
        public string SINGLE_FIELD_SEPARATORS {
            get {
                return ((string)(this["SINGLE_FIELD_SEPARATORS"]));
            }
            set {
                this["SINGLE_FIELD_SEPARATORS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int XYNLAYER_PRIORITY {
            get {
                return ((int)(this["XYNLAYER_PRIORITY"]));
            }
            set {
                this["XYNLAYER_PRIORITY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("XYN_LAYER")]
        public string XYNLAYER_NAME {
            get {
                return ((string)(this["XYNLAYER_NAME"]));
            }
            set {
                this["XYNLAYER_NAME"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ResultAddress")]
        public string RESULTADDRESSLAYER_NAME {
            get {
                return ((string)(this["RESULTADDRESSLAYER_NAME"]));
            }
            set {
                this["RESULTADDRESSLAYER_NAME"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1001")]
        public int RESULTADDRESS_PRIORITY {
            get {
                return ((int)(this["RESULTADDRESS_PRIORITY"]));
            }
            set {
                this["RESULTADDRESS_PRIORITY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#00FFFF")]
        public string XYNLAYER_LINECOLOR {
            get {
                return ((string)(this["XYNLAYER_LINECOLOR"]));
            }
            set {
                this["XYNLAYER_LINECOLOR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-2")]
        public string XYNLAYER_LINEWIDTH {
            get {
                return ((string)(this["XYNLAYER_LINEWIDTH"]));
            }
            set {
                this["XYNLAYER_LINEWIDTH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public string XYNLAYER_LINEALPHA {
            get {
                return ((string)(this["XYNLAYER_LINEALPHA"]));
            }
            set {
                this["XYNLAYER_LINEALPHA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool XYNLAYER_VISIBLE {
            get {
                return ((bool)(this["XYNLAYER_VISIBLE"]));
            }
            set {
                this["XYNLAYER_VISIBLE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1001")]
        public int COMBINEDTRANSPORTLAYER_PRIORITY {
            get {
                return ((int)(this["COMBINEDTRANSPORTLAYER_PRIORITY"]));
            }
            set {
                this["COMBINEDTRANSPORTLAYER_PRIORITY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CombinedTransport")]
        public string COMBINEDTRANSPORTLAYER_NAME {
            get {
                return ((string)(this["COMBINEDTRANSPORTLAYER_NAME"]));
            }
            set {
                this["COMBINEDTRANSPORTLAYER_NAME"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-2")]
        public int COMBINEDTRANSPORTLAYER_LINEWIDTH {
            get {
                return ((int)(this["COMBINEDTRANSPORTLAYER_LINEWIDTH"]));
            }
            set {
                this["COMBINEDTRANSPORTLAYER_LINEWIDTH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool COMBINEDTRANSPORTLAYER_TRANSPARENCY {
            get {
                return ((bool)(this["COMBINEDTRANSPORTLAYER_TRANSPARENCY"]));
            }
            set {
                this["COMBINEDTRANSPORTLAYER_TRANSPARENCY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("flaggreen.bmp")]
        public string COMBINEDTRANSPORTLAYER_START {
            get {
                return ((string)(this["COMBINEDTRANSPORTLAYER_START"]));
            }
            set {
                this["COMBINEDTRANSPORTLAYER_START"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("flagred.bmp")]
        public string COMBINEDTRANSPORTLAYER_DESTINATION {
            get {
                return ((string)(this["COMBINEDTRANSPORTLAYER_DESTINATION"]));
            }
            set {
                this["COMBINEDTRANSPORTLAYER_DESTINATION"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("xtok")]
        public string xmap_username {
            get {
                return ((string)(this["xmap_username"]));
            }
            set {
                this["xmap_username"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string xmap_password {
            get {
                return ((string)(this["xmap_password"]));
            }
            set {
                this["xmap_password"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("xtok")]
        public string xlocate_username {
            get {
                return ((string)(this["xlocate_username"]));
            }
            set {
                this["xlocate_username"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string xlocate_password {
            get {
                return ((string)(this["xlocate_password"]));
            }
            set {
                this["xlocate_password"] = value;
            }
        }
    }
}
